## springboot整合rabbitmq的基本配置
spring:
  rabbitmq:
    addresses: localhost:5672
    username: guest
    password: guest
    virtual-host: /
## 消费端配置
    listener:
      simple:
        concurrency: 1000
        ## manual:手动 ack（确认）
        acknowledge-mode: manual
        #max-concurrency: 100
        prefetch: 5

server:
  port: 8002
  servlet:
    context-path: /