server:
  port: 7010

spring:
   application:
    name: config-server
   cloud:
     config:
       server:
           # 配置git仓库地址
         git:
           uri: https://gitee.com/liuyjy/hart_market
             # 配置仓库路径
           search-paths: config
           # 访问git仓库的用户名
           username: liuyjy
           # 访问git仓库的用户密码 如果Git仓库为公开仓库，可以不填写用户名和密码，如果是私有仓库需要填写
           password: 5211314yang
  # 配置仓库的分支
       label: master
# tag::configuration-eureka[]
eureka:   #<1>
  #instance:
  #health-check-url-path: /actuator/health   #应用实例的相对运行状况检查URL路径默认为 /info/health ，2.0后actuator的地址发生了变化
  client:
    serviceUrl:
      defaultZone: http://peer1:8001/eureka/,http://peer2:8002/eureka/,http://peer3:8003/eureka/  #注册到 EurekaServer

management:
  endpoints:
    web:
      exposure:
        include: "*"   #暴露所有的端点我们可以看到更多的服务实例相关信息，
  endpoint:
    health:
      show-details: ALWAYS   #health endpoint是否必须显示全部细节